title: openQSE
author: openQSE Initiative
description: Open QHPC Software Ecosystem

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  #Docs: "#"
  #Glossary: "#"
  Meetings: "meetings"
  Community: "community"
  Resources:
    - Github:
        url: "https://github.com/openQSE"
        new-window: true
    - Slack:
        url: "https://openqse.slack.com"
        new-window: true

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/openQSE-logo.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "webmaster@openqse.org"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
#  facebook: deanattali
#  github: daattali
#  twitter: daattali
#  patreon: DeanAttali
#  youtube: "@daattali"
#  whatsapp: 15551212
#  medium: yourname
#  reddit: yourname or r/yoursubreddit
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: "invite_code" or "users/userid" or "invite/invite_code"
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname
#  strava: youruserid

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
# RSS feed description
rss-description: The goal is for openQSE to be a unified initiative to bring together vendors, collaborators, labs and universities in building an open community.

markdown: kramdown
highlighter: rouge

# Timezone
timezone: "America/New_York"

# Permalink structure
permalink: /:year-:month-:day-:title/

# Excerpt settings
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

# Date format
date_format: "%B %-d, %Y"

# Pagination
paginate: 5

# Collections
collections:
  meetings:
    output: true
    permalink: /meetings/:path/

# Default layouts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "meetings"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from build
exclude:
  - .jekyll-cache
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CLAUDE.md
  - docs/
  - _includes.bak
  - _layouts.bak
  - vendor/
  - .bundle/
